import type { Metadata } from "next";
import { Geist, Outfit } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/component/scrollbar";
import MobileActionBar from "@/component/mobile-bar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smile Baby",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "any" },
      { url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "16x16", type: "image/png" },
      { url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "icon", url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "192x192", type: "image/png" },
      { rel: "icon", url: "https://ik.imagekit.io/tnvhh8yfa/public/pregnant.png?updatedAt=1773300923014", sizes: "512x512", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17912609646"
          strategy="afterInteractive"
        />
        <Script id="google-ads" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17912609646');
          `}
        </Script>

        {/* Meta Pixel Code */}
        <Script id="meta-pixel" strategy="afterInteractive">
          {`
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1339396141252235');
fbq('track', 'PageView');
          `}
        </Script>
        {/* End Meta Pixel Code */}
        
        {/* Meta Pixel Noscript */}
        <noscript>
          <img 
            height="1" 
            width="1" 
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1339396141252235&ev=PageView&noscript=1"
            alt=""
          />
        </noscript>
        {/* End Meta Pixel Noscript */}
      </head>
      <body className={`${geistSans.variable} ${outfit.variable} antialiased`}>
        {children}
        <ScrollToTop />
        <MobileActionBar />
      </body>
    </html>
  );
}