import type { Metadata } from "next";
import { Geist, Outfit } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/component/scrollbar";
import MobileActionBar from "@/component/mobile-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smile Baby",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "/pregnant.png", sizes: "any" },
      { url: "/pregnant.png", sizes: "16x16", type: "image/png" },
      { url: "/pregnant.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "/pregnant.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "icon", url: "/pregnant.png", sizes: "192x192", type: "image/png" },
      { rel: "icon", url: "/pregnant.png", sizes: "512x512", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${outfit.variable} antialiased`}>
        {children}
        <ScrollToTop />
        <MobileActionBar />
      </body>
    </html>
  );
}
